# Generated by Django 3.1.1 on 2021-04-01 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.TextField()),
                ('key', models.TextField()),
                ('session_key', models.TextField()),
                ('workerId', models.TextField(default='')),
                ('SONA_code', models.TextField(default='')),
                ('get_args', models.TextField(default='')),
                ('notes', models.TextField(default='')),
                ('ua_header', models.TextField(default='')),
                ('screen_width', models.TextField(default='')),
                ('screen_height', models.TextField(default='')),
                ('captcha_score', models.FloatField(blank=True, null=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('condition', models.IntegerField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('birth_year', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=2, null=True)),
                ('handedness', models.CharField(blank=True, max_length=10, null=True)),
                ('post_test_purpose', models.TextField(default='')),
                ('post_test_correct', models.TextField(default='')),
                ('post_test_rule', models.TextField(default='')),
                ('post_test_pronoun', models.TextField(default='')),
                ('post_test_syntax', models.TextField(default='')),
                ('post_test_semantics', models.TextField(default='')),
                ('post_test_other', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Stimulus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(max_length=128)),
                ('item_id', models.CharField(max_length=128)),
                ('stimulus', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_time', models.FloatField()),
                ('key_press', models.IntegerField(blank=True, null=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('condition', models.IntegerField(blank=True, null=True)),
                ('trial_index', models.IntegerField(blank=True, null=True)),
                ('reversed_flag', models.BooleanField(default=False)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pipr2.participant')),
                ('stimulus', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pipr2.stimulus')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0)),
                ('language', models.TextField(default='')),
                ('proficiency', models.TextField(default='')),
                ('learned', models.TextField(default='')),
                ('active', models.TextField(default='')),
                ('proportion', models.TextField(default='')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipr2.participant')),
            ],
        ),
    ]
