# Generated by Django 3.1.1 on 2021-07-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipr3', '0002_auto_20210702_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stimulus',
            name='question_no',
        ),
        migrations.AddField(
            model_name='stimulus',
            name='continuation',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stimulus',
            name='order',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stimulus',
            name='sent_id',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stimulus',
            name='unambiguous',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
