# Generated by Django 3.1.1 on 2021-07-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipr3', '0003_auto_20210702_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='rt_cont_sp2',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='trial',
            name='rt_crit_sp2',
            field=models.FloatField(default=-1),
        ),
    ]
