# Generated by Django 3.1.1 on 2021-07-05 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipr3', '0004_auto_20210702_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trial',
            old_name='time_elapsed',
            new_name='passage_reading_time',
        ),
    ]
