# Generated by Django 3.1.1 on 2020-09-24 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pronouns', '0004_trial_trial_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='Feedback',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='participant',
            name='purpose',
            field=models.TextField(default=''),
        ),
    ]
