# Generated by Django 3.1.1 on 2020-09-24 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pronouns', '0005_auto_20200924_2152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='Feedback',
            new_name='feedback',
        ),
    ]
