# Generated by Django 3.1.1 on 2021-07-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipr3', '0005_auto_20210705_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='conditions',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='vision',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
