# Generated by Django 3.1.1 on 2020-09-24 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pronouns', '0006_auto_20200924_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='reversed_flag',
            field=models.BooleanField(default=False),
        ),
    ]
