# Generated by Django 3.1.1 on 2021-07-06 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipr3', '0006_auto_20210706_1042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='post_test_correct',
            new_name='post_test_example',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='post_test_rule',
            new_name='post_test_inconsistent',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='post_test_semantics',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='post_test_syntax',
        ),
    ]
