# Generated by Django 3.1.1 on 2021-07-06 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipr3', '0007_auto_20210706_1143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='condition',
            new_name='list_idx',
        ),
    ]
