# Generated by Django 3.1.1 on 2020-09-24 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pronouns', '0007_trial_reversed_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
