# Generated by Django 3.1.1 on 2021-07-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipr3', '0008_auto_20210706_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='rt_cont_sp3',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='trial',
            name='rt_crit_sp3',
            field=models.FloatField(default=-1),
        ),
    ]
