# Generated by Django 3.1.1 on 2020-10-20 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pronouns', '0008_participant_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='workerId',
            field=models.TextField(default=''),
        ),
    ]
