# Generated by Django 3.1.1 on 2020-10-22 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pronouns', '0009_participant_workerid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='feedback',
            new_name='post_test_other',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='purpose',
            new_name='post_test_purpose',
        ),
    ]
