# Generated by Django 3.1.1 on 2021-07-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipr3', '0010_auto_20210709_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='adhd',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='asd',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='dyslexia',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
