# Generated by Django 3.1.1 on 2020-10-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pronouns', '0010_auto_20201022_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='post_test_correct',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='participant',
            name='post_test_pronoun',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='participant',
            name='post_test_rule',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='participant',
            name='post_test_semantics',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='participant',
            name='post_test_syntax',
            field=models.TextField(default=''),
        ),
    ]
