# Generated by Django 3.1.1 on 2021-07-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipr3', '0011_auto_20210709_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='condition',
            field=models.CharField(choices=[('UN', 'Unambiguous'), ('AM', 'Ambiguous'), ('NA', 'Unassigned')], default='NA', max_length=2),
        ),
    ]
