# Generated by Django 3.1.1 on 2020-10-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pronouns', '0011_auto_20201022_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='get_args',
            field=models.TextField(default=''),
        ),
    ]
