# Generated by Django 3.1.1 on 2021-08-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipr3', '0012_participant_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='native_english',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='vision_reason',
            field=models.TextField(default=''),
        ),
    ]
