# Generated by Django 3.1.1 on 2020-11-24 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pronouns', '0013_participant_handedness'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='SONA_code',
            field=models.TextField(default=''),
        ),
    ]
