# Generated by Django 3.1.1 on 2021-08-24 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pipr3', '0013_auto_20210823_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scale', models.CharField(choices=[('VVIQ', 'Unambiguous'), ('OSIVQ', 'Ambiguous')], max_length=10)),
                ('item_id', models.CharField(max_length=10)),
                ('response', models.IntegerField()),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipr3.participant')),
            ],
        ),
    ]
